site_name: SmlCoke Home # 改成你的
site_url: https://smlcoke.com
site_author: SmlCoke

theme:
  name: material
  language: zh
  features:
    - navigation.tabs # 将左侧导航栏变为顶部的标签页，看起来更像官网
    - navigation.top # 添加返回顶部按钮
    - header.autohide # 页面向下滚动时自动隐藏导航栏

# 配置插件（启用搜索和博客功能）
plugins:
  - search
  - blog

# 配置 Markdown 扩展（启用数学公式支持）
markdown_extensions:
  - nl2br # 将换行符转换为 <br> 标签，启用单回车换行支持
  - pymdownx.arithmatex:
      generic: true

# 引入自定义 CSS（用于背景动画和按钮）
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css # 添加 KaTeX CSS

extra_javascript:
  - javascripts/extra.js
  - https://unpkg.com/katex@0/dist/katex.min.js # 先引入 KaTeX 核心
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js # 引入 KaTeX 自动渲染插件
  - javascripts/katex.js # 最后引入初始化脚本
  
nav:
  - 首页: index.md
  - 博客: blog/ # 博客插件会自动接管这个目录
  - 微电子: 
    - 信号与系统:
      - 常系数线性微分方程: me/SS/Linear_Differential_Equations/index.md
      - 傅里叶变换: me/SS/FT/index.md
    - 数字芯片设计术语和流程: me/DIC/Glossary.md
    - Verilog HDL 基础: me/verilog/Study_note.md
  - 机器学习: ml/Basic/index.md
  - 计算机视觉: ml/CV/index.md
  - Rust:
    - Rust 学习笔记: rust/Study.md
