site_name: SmlCoke Home # æ”¹æˆä½ çš„
site_url: https://smlcoke.com
site_author: SmlCoke

theme:
  name: material
  language: zh
  features:
    - navigation.tabs # å°†å·¦ä¾§å¯¼èˆªæ å˜ä¸ºé¡¶éƒ¨çš„æ ‡ç­¾é¡µï¼Œçœ‹èµ·æ¥æ›´åƒå®˜ç½‘
    - navigation.top # æ·»åŠ è¿”å›é¡¶éƒ¨æŒ‰é’®
    - header.autohide # é¡µé¢å‘ä¸‹æ»šåŠ¨æ—¶è‡ªåŠ¨éšè—å¯¼èˆªæ 
    - navigation.indexes # å…è®¸ index.md ä½œä¸ºåˆ†åŒºé¦–é¡µ
    - content.code.copy # ğŸ”¥ æ–°å¢ï¼šä»£ç å—å³ä¸Šè§’çš„ä¸€é”®å¤åˆ¶æŒ‰é’®

# é…ç½®æ’ä»¶ï¼ˆå¯ç”¨æœç´¢å’Œåšå®¢åŠŸèƒ½ï¼‰
plugins:
  - search
  - blog

# é…ç½® Markdown æ‰©å±•ï¼ˆå¯ç”¨æ•°å­¦å…¬å¼æ”¯æŒï¼‰
markdown_extensions:
  - nl2br # å°†æ¢è¡Œç¬¦è½¬æ¢ä¸º <br> æ ‡ç­¾ï¼Œå¯ç”¨å•å›è½¦æ¢è¡Œæ”¯æŒ
  - pymdownx.arithmatex:
      generic: true
  # ğŸ‘‡ ä¸‹é¢å…¨æ˜¯è®©ç½‘é¡µå˜ç¾çš„é­”æ³•æ‰©å±• ğŸ‘‡
  - admonition # æå…¶æ¼‚äº®çš„æç¤º/è­¦å‘Šæ¡†ï¼
  - pymdownx.details # å…è®¸æŠ˜å æç¤ºæ¡†
  - pymdownx.superfences # é«˜çº§ä»£ç å—
  - pymdownx.highlight: # ä»£ç é«˜äº®ç¾åŒ–
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # è¡Œå†…ä»£ç é«˜äº®
  - pymdownx.mark # å…è®¸ä½¿ç”¨ ==é«˜äº®æ–‡å­—==
  - pymdownx.tilde # å…è®¸ä½¿ç”¨ ~~åˆ é™¤çº¿~~
  - attr_list # å…è®¸ç»™å›¾ç‰‡åŠ å±…ä¸­ç­‰æ ·å¼

# å¼•å…¥è‡ªå®šä¹‰ CSSï¼ˆç”¨äºèƒŒæ™¯åŠ¨ç”»å’ŒæŒ‰é’®ï¼‰
extra_css:
  - stylesheets/extra.css?v=20260224 # æ¯æ¬¡æ›´æ–°æ—¶ï¼Œæ³¨æ„ä¿®æ”¹?væŸ¥è¯¢å‚æ•°ï¼Œé˜²æ­¢æµè§ˆå™¨ç›´æ¥åˆ©ç”¨æœ¬åœ°æ—§ç¼“å­˜
  - https://unpkg.com/katex@0/dist/katex.min.css # æ·»åŠ  KaTeX CSS

extra_javascript:
  - javascripts/extra.js
  - https://unpkg.com/katex@0/dist/katex.min.js # å…ˆå¼•å…¥ KaTeX æ ¸å¿ƒ
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js # å¼•å…¥ KaTeX è‡ªåŠ¨æ¸²æŸ“æ’ä»¶
  - javascripts/katex.js # æœ€åå¼•å…¥åˆå§‹åŒ–è„šæœ¬
  
nav:
  - é¦–é¡µ: index.md
  - åšå®¢: blog/ # åšå®¢æ’ä»¶ä¼šè‡ªåŠ¨æ¥ç®¡è¿™ä¸ªç›®å½•
  - å¾®ç”µå­: 
    - me/index.md
    - ä¿¡å·ä¸ç³»ç»Ÿ: me/SS/index.md
    - æ•°å­—èŠ¯ç‰‡è®¾è®¡æœ¯è¯­å’Œæµç¨‹: me/DIC/Glossary.md
    - Verilog HDL åŸºç¡€: me/verilog/Study_note.md
  - æœºå™¨å­¦ä¹ :
    - ml/Basic/index.md
    - å…¨è¿æ¥ç¥ç»ç½‘ç»œ: ml/Basic/ch1_Full_Connected_NN/ch1_ç¥ç»ç½‘ç»œä¸æ·±åº¦å­¦ä¹ åŸºç¡€.md
    - ä¼˜åŒ–: ml/Basic/ch2_Optimization/ch2_2_Optimization.md
    - CNN: ml/Basic/ch3_CNN/ch3_CNN.md
    - Self-Attention: ml/Basic/ch4_Self_Attention/ch4_self_attentionåŸºç¡€.md
    - Transformer: ml/Basic/ch5_Transformer/ch5_transformeråŸºç¡€.md
  - è®¡ç®—æœºè§†è§‰:
    - ml/CV/index.md
    - ResNet: ml/CV/ResNet/notes.md
    - DenseNet: ml/CV/DenseNet/notes.md
    - YOLO v1: ml/CV/YOLO/YOLO.md
    - YOLO v2: ml/CV/YOLO/YOLOv2.md
    - YOLO v3: ml/CV/YOLO/YOLOv3.md
    - ViT: ml/CV/VIT/ViT.md
    - PFLD: ml/CV/PFLD/PFLD.md
  - Rust:
    - Rust å­¦ä¹ ç¬”è®°: rust/notes/Study.md
    - Rust åŠ å¯†/è§£å¯†åœ¨çº¿å·¥å…·: rust/crypto/
